source 'https://github.com/JY726/LJYSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'LJYAuthorKit_Category_Example' do
  pod 'LJYAuthorKit_Category', :path => '../'

  target 'LJYAuthorKit_Category_Tests' do
    inherit! :search_paths

    
  end
end
